docs/design/proposal.md
docs/meetings/M01.md
docs/meetings/M02.md

chore(docs): migrate meeting notes and project proposal

---

book.toml
docs/meetings/M01.md
docs/meetings/M02.md

- removed numbering from side bar
- updated meeting notes for consistency

📖 docs: updated docs

---

docs/client-meetings/CM01.md

TODO: link in write up from #7

docs: client meeting 1 notes

---

.github/workflows/pr_compliance.yml

Check for the following:
- PR title must comply to [conventional commit](https://www.conventionalcommits.org/en/v1.0.0/)
- PR must have closing keyword for an issue
- test
Closes #25

ci(compliance): added PR compliance checker

---

docs/design/mvp-summary-for-client.md

docs: mvp summary

---

docs/design/cloud_infra.md

docs: cloud infrastructure

---

.github/workflows/client_test.yml

ci: add automated test for react

---

.github/workflows/mdbook.yml
book.toml
docs/SUMMARY.md
docs/design/database.md

docs: er diagram

---

docs/SUMMARY.md
docs/design/user_stories.md

docs: migrate user stories

---

docs/design/orm.md

docs: add orm discussion notes

---

.github/workflows/pr_compliance.yml

fix: modify strict PR body regex

---

docs/SUMMARY.md
docs/design/glossary.md
docs/misc/useful-links.md

docs: added new section for useful links around the project

---

server/src/models/activities/activity.controller.ts

fix: update resource to be set in controller decorator

---

server/package.json
server/src/auth/auth.module.ts
server/src/auth/constants.ts
server/src/auth/jwt-auth.guard.ts
server/src/auth/jwt.strategy.ts
server/yarn.lock

resolves #54 
added auth guard
In some controller section (ex. `feature.controler.ts`):
- Import the following
```ts
import { UseGuards } from '@nestjs/common';
import { JwtAuthGuard } from 'src/auth/jwt-auth.guard';
```
- At some route decorator (ex. `@Controller(...)`, `@Get(...)`, `@Post(...)`, etc), add `@UseGuards(JwtAuthGuard)` above it
When you try to reach the desired route, it should yield an unauthorized error. To get a valid case, generate a jwt token from the private key located in constants.ts or use the following example jwt:
`eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJzdWIiOiIxMjM0NTY3ODkwIiwibmFtZSI6IkpvaG4gRG9lIiwiaWF0IjoxNTE2MjM5MDIyfQ.Hy1qGnC3zWDQ7HNxdUXMSriG437CKpMPmQFzky_azUc`

feat: authentication middleware

---

server/prisma/schema.prisma
server/src/app.module.ts
server/src/models/features/feature.service.ts
server/src/models/roles/role.controller.ts
server/src/models/roles/role.dto.ts
server/src/models/roles/role.module.ts
server/src/models/roles/role.service.ts

resolves #57 
added main crud endpoints for managing roles

feat: crud endpoints for roles

---

server/prisma/schema.prisma
server/prisma/seed.ts
server/src/models/roles/role.dto.ts

resolves #98 
Added some seed data for roles, fixed role modeling a bit
NA

fix: added role seed and fix some issues

---

server/src/app.module.ts
server/src/auth/auth.controller.ts
server/src/auth/auth.dto.ts
server/src/auth/auth.module.ts
server/src/auth/auth.service.ts
server/src/auth/jwt.strategy.ts

resolves #64 
- auth routes
- login
- get user details
- updated validation guard to check if user is in database

feat: first pass of auth routes

---

server/package.json
server/prisma/schema.prisma
server/src/app.module.ts
server/src/models/ip/ip.controller.ts
server/src/models/ip/ip.dto.ts
server/src/models/ip/ip.module.ts
server/src/models/ip/ip.service.ts

resolves #59 
CRUD endpoints for IP allowlist.   
Also added the `prisma db push` command to sync with mongodb on `@unique` attributes / indices
More here [prisma release 3.4.0 notes](https://github.com/prisma/prisma/releases/tag/3.4.0)

feat: ip allowlist crud endpoints

---

client/src/main.tsx
client/src/pages/allowlist/index.tsx

Resolves #63
Create base UI for the allowlist page

feat: Allowlist UI

---

server/prisma/schema.prisma
server/src/app.module.ts
server/src/models/products/product.controller.ts
server/src/models/products/product.dto.ts
server/src/models/products/product.module.ts
server/src/models/products/product.service.ts
server/src/models/products/variants/variant.controller.ts
server/src/models/products/variants/variant.dto.ts
server/src/models/products/variants/variant.module.ts
server/src/models/products/variants/variant.service.ts

feat: integrate products endpoint with variants

---

client/src/components/drawer/AdminList.tsx
client/src/data/features.ts
client/src/data/index.ts
client/src/data/roles.ts
client/src/main.tsx
client/src/pages/role-details/RoleDetails.tsx
client/src/pages/roles-list/RolesList.tsx
client/src/types/feature.ts
client/src/types/index.ts
client/src/types/roles.ts
server/src/models/roles/role.controller.ts
server/src/models/roles/role.service.ts

resolves #62 
Run server and go to `/roles` route

feat: first pass at roles ui

---

server/prisma/seed.ts
server/src/auth/auth.controller.ts
server/src/auth/auth.module.ts
server/src/auth/auth.service.ts
server/src/auth/constants.ts
server/src/auth/ip.guard.ts
server/src/auth/jwt.strategy.ts
server/src/auth/role.decorator.ts
server/src/auth/role.guard.spec.ts
server/src/auth/role.guard.ts
server/src/main.ts
server/src/models/ip/ip.module.ts
server/src/models/ip/ip.service.ts
server/src/models/staff/staff.controller.ts
server/src/models/staff/staff.service.ts

resolves #56 
- Added a new guard for roles and permissions
- Added a new guard for IP address check
- Added decorators for quickly setting up authorization for an endpoint
- Added decorators for skipping IP checks

feat: auth guards for server 😻

---

client/src/components/save-bar/save-bar.tsx
client/src/pages/staff-details/StaffDetails.tsx
client/src/pages/staff-list/StaffInvite.tsx
client/src/pages/staff-list/StaffList.tsx
client/src/utils/clipboard/use-clipboard.ts
client/src/utils/index.ts
client/src/utils/validation.ts

feat: added staff page improvements

---

server/src/auth/auth.controller.ts
server/src/auth/auth.service.ts

feat: add roles related information to auth related queries

---

client/src/data/features.ts
client/src/data/roles.ts
client/src/data/staff.ts
client/src/pages/role-details/RoleDetails.tsx
client/src/pages/roles-list/RolesList.tsx
client/src/pages/staff-details/StaffDetails.tsx
client/src/types/roles.ts
client/src/types/staff.ts
docker-compose.yml
server/Seed.Dockerfile

chore: data files clean up + prisma db push

---

packages/c-form/src/templates/v1.ts
server/prisma/schema.prisma

feat: updated db schema for form + responses

---

server/prisma/schema.prisma
server/src/app.module.ts
server/src/models/forms/form.controller.ts
server/src/models/forms/form.dto.ts
server/src/models/forms/form.module.ts
server/src/models/forms/form.service.ts

resolves #132 
Added form related endpoints

feat: first pass at form endpoints

---

client/.eslintrc.js
client/src/__tests__/form-builder.spec.tsx
client/src/__tests__/testUtil.tsx
client/src/components/dialog/ConfirmDialog.tsx
client/src/components/form-builder/form-builder.tsx
client/src/components/form-builder/form-section.tsx
client/src/components/save-bar/save-bar.tsx
client/src/components/tabs/TabPanel.tsx
client/src/pages/allowlist/AllowlistAdd.tsx
client/src/pages/inventory/InventoryCreate.tsx
client/src/pages/inventory/InventoryEdit.tsx
client/src/pages/inventory/InventoryList.tsx
client/src/pages/inventory/VariantCreate.tsx
client/src/pages/roles-list/RolesList.tsx
client/src/store/index.ts
client/src/types/index.ts
client/src/types/util.ts
server/.eslintrc.js
server/src/auth/role.guard.spec.ts
server/src/main.ts
server/src/models/responses/response.controller.ts
server/src/models/responses/response.service.ts
server/src/models/roles/role.dto.ts
server/src/models/staff/staff.controller.ts
server/src/models/staff/staff.dto.ts

resolves #157 
resolves #159 
Clean up a bunch of lint issues

fix: fix a bunch of lint issues and mark them as error 🧹

---

server/package.json
server/src/auth/auth.module.ts
server/src/auth/ip.guard.ts
server/src/models/activities/activity.controller.ts
server/src/models/features/feature.controller.ts
server/src/models/forms/form.controller.ts
server/src/models/ip/ip.controller.ts
server/src/models/ip/ip.module.ts
server/src/models/ip/ip.service.ts
server/src/models/products/product.controller.ts
server/src/models/products/variants/variant.controller.ts
server/src/models/responses/response.controller.ts
server/src/models/staff/staff.controller.ts
server/src/models/staff/staff.module.ts
server/test/app.e2e-spec.ts
server/test/feature.e2e-spec.ts
server/test/testClient.ts
server/yarn.lock

- updated imports so normal unit tests can run
- updated e2e tests to test running server
- introduced yum to test schema
resolves #140 
In the server dir, run:
- `yarn run test`
- `yarn run test:e2e`

feat: updated tests

---

.env.development
docker-compose.yml
server/package.json
server/prisma/seed.common.ts
server/prisma/seed.dev.ts
server/prisma/seed.ts

resolves #167 
- Improved env file for docker compose
- Seed now respects the environment.
Simply run docker compose and the seeding should work as expected

build: added the ability to seed data based on env 🌱

---

client/src/components/loading-card/LoadingCard.tsx
client/src/components/loading-card/index.ts
client/src/pages/allowlist/Allowlist.tsx
client/src/pages/roles-list/RolesList.tsx
client/src/pages/staff-list/StaffList.tsx

resolves #181 
generic case when no results are found
generic case when page is fetching initial data
generic case when an error times out

feat(#181): add loading and error state during page request

---

server/package.json
server/src/app.module.ts
server/src/health/health.controller.spec.ts
server/src/health/health.controller.ts
server/src/health/health.module.ts
server/src/health/prisma-health-indicator/prisma-health-indicator.service.spec.ts
server/src/health/prisma-health-indicator/prisma-health-indicator.service.ts
server/src/main.ts
server/yarn.lock

resolves #173 
Added a few health check endpoints
```
curl http://localhost:3001/health
```

feat: added health check endpoints 👩🏻‍⚕️

---

.env.development
server/src/auth/role.decorator.ts
server/src/auth/role.guard.ts
server/src/environment.d.ts
server/src/main.ts
server/src/models/activities/activity.controller.ts
server/src/models/customers/customer.controller.ts
server/src/models/features/feature.controller.ts
server/src/models/forms/form.controller.ts
server/src/models/ip/ip.controller.ts
server/src/models/products/product.controller.ts
server/src/models/products/variants/variant.controller.ts
server/src/models/responses/response.controller.ts
server/src/models/roles/role.controller.ts
server/src/models/staff/staff.controller.ts

resolves #172 
- Added auth decorator to all classes
- Enable IP guard

feat: added authentication capabilities to endpoints 🔐

---

server/src/models/forms/form.controller.ts

resolves #166 
Get add c-form validation checks into for POST and PUT endpoints

feat: add c-form validation to backend routes

---

server/package.json
server/yarn.lock

fix: added ajv to server

---

client/src/components/account-menu/AccountMenu.tsx
client/src/components/account-menu/index.ts
client/src/components/app-bar/index.tsx
client/src/components/drawer/AdminList.tsx
client/src/components/drawer/index.tsx
client/src/components/privileged-route/PrivilegedRoute.tsx
client/src/components/protected-route/ProtectedRoute.tsx
client/src/main.tsx
client/src/pages/login/index.tsx
client/src/pages/not-authorized/NotAuthorized.tsx
client/src/store/index.ts
client/src/types/roles.ts
client/src/types/staff.ts
client/src/utils/auth.ts
client/src/utils/index.ts
client/src/utils/permission.ts
client/src/utils/storage-helpers.ts

resolves #209 
https://user-images.githubusercontent.com/20260270/173379162-7e0b4348-9c01-4477-afa7-2ee28552a507.mov
In the first half I am logged in with Receptionist in which I am unable to access the security route. After logging out and logging back in with admin role, I am able to access the Security section
UPDATE: added permissions in sidebar
With role NOOB (nothing but customer permission)
With role ADMIN (all privleges)

feat(#209): integrate permissions and authentication in frontend

---

client/src/pages/role-details/RoleDetails.tsx

fix(#203): save bar covering delete section role page

---

infrastructure/kubernetes/staging/chronicle-backend.yaml
infrastructure/kubernetes/staging/chronicle-frontend.yaml

fix: update resource requests and spot usage in app maifest

---

client/package.json
client/src/components/account-menu/AccountMenu.tsx
client/src/components/activities-table/ActivitiesTable.tsx
client/src/components/products-table/ProductsTable.tsx
client/src/pages/inventory/ActivityEdit.tsx
client/src/pages/inventory/InventoryList.tsx
client/src/pages/inventory/VariantCreate.tsx
client/src/types/product.ts
client/src/utils/format.ts
server/prisma/schema.prisma

resolves #221 
- Change inventory table to list products and not all variants
- Product info includes full price range
- Updated date formatting
- Removed a few unnecessary columns

fix: improve inventory table

---

client/package.json
client/src/main.tsx
client/src/pages/customer-details/CustomerDetails.tsx
client/src/pages/inventory/ProductEdit.tsx
client/yarn.lock

resolves #230 
- Implemented the `notistack` library to enable creating snackbar notifications with an imperative API

feat: added imperative snackbar hook

---

client/src/data/auth.ts
client/src/pages/login/index.tsx
client/src/utils/storage-helpers.ts

resolves #224 
https://user-images.githubusercontent.com/20260270/191639421-8c93810b-2f8c-439f-9983-e57b36431c8a.mov

fix(#224): redirect user to login when token expires

---

client/src/pages/activity-entry-list/ActivityEntryList.tsx
docs/SUMMARY.md
docs/design/data_analytics.md
server/src/analytics/analytics.controller.ts
server/src/analytics/analytics.module.ts
server/src/analytics/views/activity.ts
server/src/app.module.ts

resolves #246 
Added a prototype endpoint to evaluate design and code pattern with the team. This is quite easy to implement not gonna lie.
- Quick prototype endpoint

feat: added a prototype for the mvp analytics engine

---

client/src/data/activity-entry.ts
client/src/pages/activity-entry-list/ActivityEntryList.tsx
client/src/pages/activity-entry-list/components/ActivityEntryTable.tsx
server/src/models/activity-entry/activity-entry.controller.ts

resolves #231 
- Added new tab view, disabled the behavior that causes author to be overwritten on update

feat: added the ability to show all entries and my own entries

---

client/src/components/form-inputs/FormInputField.tsx
client/src/components/form-inputs/form-inputs.tsx
client/src/components/form-viewer/form-fields-factory.tsx
client/src/pages/inventory/ActivityBase.tsx
client/src/pages/inventory/VariantCreate.tsx
client/src/pages/login/index.tsx

resolves #250
- Removed `numberField` attribute from `FormInputField`
- Added a new `type` attribute
- Support all MUI supported input types now

fix: improve form input to allow more types

---

client/src/components/form-inputs/FormInputField.tsx
client/src/pages/login/index.tsx
server/Seed.Dockerfile
server/prisma/seed.dev.ts

resolves #260 
- add autofocus to login page
- fix seed data so data is being seeded correctly

fix: added autofocus on login page + seed data fix

---

client/src/components/form-builder/form-field.tsx
client/src/components/form-builder/form-section.tsx
client/src/pages/forms/FormBase.tsx

resolves #242 
- Added buttons for moving fields in a section
- Made sure we can disable some of those buttons

feat: implemented field reordering feature

---

client/src/components/form-builder/components/StaticMultipleChoiceBuilder.tsx
client/src/components/form-builder/form-field.tsx

resolves #243 
https://user-images.githubusercontent.com/11084692/196006029-263e6dfe-d1b4-4953-82f0-dc655b3b59e4.mp4
- Added the ability to press enter to get a new option for static forms

feat: on enter add new option for static form entries

---

client/src/components/page-header/PageHeader.tsx
client/src/pages/role-details/RoleDetails.tsx
server/src/models/roles/role.dto.ts

resolves #213 
resolves #202 
resolves #275
- Made role editing work more fluently
- Remove unused form element on role page
- Clean up role update dto model
- More minor improvements

fix: fix a few bugs across the UI, mostly with roles

---

docs/SUMMARY.md
docs/user-manual/login.md
docs/user-manual/staff-management.md

resolves #273
Added more documentation

docs: added staff details docs

---

client/src/pages/allowlist/Allowlist.tsx
client/src/pages/allowlist/AllowlistAdd.tsx
server/src/models/ip/ip.service.ts

resolves #286
- fixed an issue causing delete to not work correctly
- fixed an issue with ip missing cidr prefix
- improve allowlist page ux

fix: fix ip allowlist issues

---

client/src/__tests__/form-builder.spec.tsx
client/src/components/form-builder/components/FormFieldOptionsMenu.tsx
client/src/components/form-builder/form-field.tsx
client/src/components/form-builder/form-section.tsx

resolves #259 
https://user-images.githubusercontent.com/11084692/196267475-fafc40f1-5a8f-423a-9420-ae54b5caac2f.mp4
- Added the ability to duplicate a field
- Moved some lesser used field options to an expandable menu

feat: added the ability to dup field

---

client/src/components/activity-card/activity-card.tsx
client/src/components/dialog/AlertDialog.tsx
client/src/components/dialog/ConfirmDialog.tsx
client/src/components/form-inputs/FormInputField.tsx
client/src/components/use-alert/UseAlertContext.tsx
client/src/components/use-alert/index.ts
client/src/main.tsx
client/src/pages/activity-entry-details/ActivityEntryDetails.tsx
client/src/pages/inventory/ActivityBase.tsx
client/src/pages/inventory/ActivityEdit.tsx
client/src/types/activity.ts
client/src/utils/compare-object.ts
server/prisma/fixtures/dev/activities.ts
server/src/models/activities/activity.controller.ts
server/src/models/activities/activity.dto.ts
server/src/models/activities/activity.service.ts

resolves #291 
Activity entry changes
https://user-images.githubusercontent.com/11084692/196739493-edd74849-0f2d-4fa0-a1d8-d88cf6f94788.mp4
Activity details changes
- Made activity inventory data immutable
- Added UI and UX flow for legacy activities
- Added UI and UX flow for in-use activities

feat: made activity inventory data immutable

---

client/src/components/form-inputs/FormSelect.tsx
client/src/components/form-viewer/form-fields-factory.tsx
client/src/components/gender-select/GenderSelect.tsx
client/src/components/index.ts
client/src/pages/customer-details/CustomerDetails.tsx
client/src/pages/forms/FormBase.tsx
client/src/pages/staff-details/StaffDetails.tsx

resolves #279 
https://user-images.githubusercontent.com/11084692/196701404-9cbe73b9-0af8-40d8-90c1-ed4fa196c1eb.mp4
- Added field for handling customer gender information

feat: added customer gender handling

---

client/.env.development
client/.env.production
client/src/components/app-bar/index.tsx
client/src/components/form-inputs/FormInputField.tsx
client/src/data/activity-entry.ts
client/src/data/charge.ts
client/src/pages/activity-entry-details/ActivityEntryChargeDialog.tsx
client/src/pages/activity-entry-details/ActivityEntryDetails.tsx
client/src/pages/activity-entry-details/components/TipButton.tsx
client/src/types/activity-entry.ts
client/src/vite-env.d.ts
server/src/models/activity-entry/activity-entry.controller.ts

resolves #300
https://user-images.githubusercontent.com/11084692/197110376-3971330d-b9fc-4675-ac94-502d40b8e17f.mov
- Added UI for creating charges
- Added UI elements for AE after charges have been created

feat: added UI for creating charges

---

docs/SUMMARY.md
docs/design/immutable_inventory_customer_balance.md

docs: added design doc on inventory versioning & customer balance management

---

client/src/components/index.ts
client/src/pages/allowlist/Allowlist.tsx
client/src/pages/role-details/RoleDetails.tsx
client/src/pages/roles-list/RolesList.tsx
client/src/pages/staff-details/StaffDetails.tsx
client/src/pages/staff-list/StaffList.tsx
server/src/models/features/feature.controller.ts

resolves #318
- lock buttons on readonly UI

feat: made security features read-only

---

client/src/components/index.ts
client/src/pages/activity-entry-details/ActivityEntryDetails.tsx
client/src/pages/activity-entry-list/ActivityEntryList.tsx

resolves #317 
Made activity entry fields readonly

fix: made activity entry UI readonly

---

client/src/components/drawer/DrawerEntry.tsx
server/prisma/fixtures/common/roles.ts
server/prisma/seed.common.ts

resolves #323
- Fix common seed data (why do we have a unique constraint on role names?)
- Fix an issue causing side nav options not showing up for super users

fix: fix more issues found with seeding

---

client/src/components/form-builder/FieldTypeSelect.tsx
client/src/components/form-builder/components/FormFieldOptionsMenu.tsx
client/src/components/form-builder/components/StaticMultipleChoiceBuilder.tsx
client/src/components/form-builder/form-builder.tsx
client/src/components/form-builder/form-field.tsx
client/src/components/form-builder/form-section.tsx
client/src/components/use-permission/UsePermissionContext.tsx
client/src/pages/forms/Forms.tsx

resolves #325
Disable all fields and buttons when user can only read

fix: made custom form UI read only

---

client/src/components/save-bar/use-save-bar.tsx
client/src/pages/activity-entry-details/ActivityEntryChargeDialog.tsx
client/src/pages/activity-entry-details/ActivityEntryDetails.tsx
client/src/pages/inventory/ProductEdit.tsx
client/src/pages/inventory/VariantCreate.tsx
client/src/types/product.ts
server/src/models/activity-entry/activity-entry.controller.ts
server/src/models/products/product.controller.ts
server/src/models/products/product.service.ts
server/src/models/products/variants/variant.controller.ts
server/src/models/products/variants/variant.service.ts

resolves #321
- Some minor UI changes and some endpoint updates

fix: prevent user from deleting products and variants that are in use

---

client/nginx.conf

fix: disabled index.html file caching

---

docs/user-manual/login.md

add doc to reset your password manually

docs(login): add steps on how to reset your password

---

client/package.json
client/src/__tests__/auth.spec.tsx
client/src/__tests__/permission.spec.ts
client/src/__tests__/random.spec.ts
client/src/__tests__/storage-helpers.spec.ts
client/src/__tests__/storage.spec.ts
client/src/pages/role-details/RoleDetails.tsx
client/src/pages/roles-list/RolesList.tsx
client/src/testing-utils/local-storage-mock.ts
client/src/types/roles.ts
client/src/utils/auth.ts
client/src/utils/permission.ts
client/src/utils/random.ts
client/yarn.lock
cypress/integration/role.spec.ts
docs/design/user_stories.md
server/src/models/roles/role.controller.ts
server/src/models/roles/role.service.ts

resolves #335
- Added more automated unit tests
- Added more cypress tests

test: added more automate tests

---

client/src/components/audit-row/AuditRow.tsx
client/src/components/audit-row/resolver.tsx
client/src/components/audit-row/resolvers/resolveAddIPToAllowList.tsx
client/src/components/audit-row/resolvers/resolveCreateForm.tsx
client/src/components/audit-row/resolvers/resolveCreateRole.tsx
client/src/components/audit-row/resolvers/resolveUpdateForm.tsx
client/src/components/audit-row/type.ts
client/src/pages/staff-details/StaffDetails.tsx
server/src/models/audit/audit.service.ts

resolves #342 
- added a few missing guard

fix: added a few missing resolvers

---

client/src/components/form-viewer/form-viewer.tsx
client/src/components/save-bar/save-bar.tsx
client/src/vars.ts
server/src/models/customers/customer.controller.ts

feat: added guided access form

---

.github/workflows/mdbook.yml

fix: pin mermaid version

---

client/.env.development
client/.env.production

resolves #356 
Fix company name spelling

fix: fix invalid names in the application

---

docs/design/database.md

check out preview here: https://github.com/KonomiAI/Chronicle/blob/5e9803db3748dc8321cf87ed26c3ddb781fc8c8e/docs/design/database.md

docs: update er diagram
